/*
 * Stepper_config.h
 *
 *  Created on: Feb 14, 2021
 *      Author: Kishk
 */

#ifndef HAL_06__STEPPER_STEPPER_CONFIG_H_
#define HAL_06__STEPPER_STEPPER_CONFIG_H_

#define STEPPER_u8_BLUE_COIL		DIO_PORTB_PIN0
#define STEPPER_u8_PINK_COIL		DIO_PORTB_PIN1
#define STEPPER_u8_YELLOW_COIL		DIO_PORTB_PIN2
#define STEPPER_u8_ORANGE_COIL		DIO_PORTB_PIN3


#endif /* HAL_06__STEPPER_STEPPER_CONFIG_H_ */
